### ISSUE TITLE
Skip jobs that access privileged secrets if triggered by Dependabot

### ISSUE THREAD

**Issue by hknutsen** [equinor/ops-actions#516]
Jobs triggered by Dependabot can't access Actions secrets. This is to prevent Dependabot from updating a dependency to a version containing malicious code which could steal those secrets.

If you want Dependabot to access secrets, you have to explicitly create separate Dependabot secrets:

![image](https://github.com/equinor/ops-actions/assets/46495473/1efa64f6-06a9-4b68-803e-0f5ed020b8bb)

If a job triggered by Dependabot tries to access Actions secrets, that job will fail.

Consider adding a conditional `if: github.actor != 'dependabot[bot]'` to jobs that access secrets to prevent malicious code from accessing secrets that it shouldn't, e.g. Azure credentials.

Could be considered a fix, since it prevents jobs that access secrets from failing if triggered by Dependabot.

Consider updating security section in best practices to always skip jobs that access secrets if triggered by Dependabot (or if it requires a GITHUB_TOKEN with write access to the repository).

## Tasks

- [x] #515
- [x] #517 

## References

- https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by sefornes** [comment]
Seems like a good idea, if Dependabot still works as intended afterwards.

**Comment by hknutsen** [comment]
@sefornes Dependabot will still work, it just won't run jobs that access secrets that grant privileged access. #517 Should explain it quite well, I hope.

**Comment by kov117** [comment]
i support this, properly a good secure method anyway, so i give two thumps up 👍🏼 👍🏼
